name: biohub
channels:
  - conda-forge
dependencies:
  - python=3.11
  - numpy
  - scipy
  - scikit-image
  - pandas
  - zarr
  - numcodecs
  - networkx
  - matplotlib
  - tqdm
  - pytest
  - pip
  - pip:
      - -r requirements.txt
